### PR TITLE
Added 'thread' functionality

### PR DESCRIPTION
**Pull request by seanpcoyle**
Added a forum-like thread section.  

_Completed:_
- Currently, users may only view existing threads.
- Comments on threads are visible

_Todo:_
- Allow users to create threads
- Find somewhere to link to threads from main page
- Incorporate main sidebar into layout

_Known issues:_
 None

### CODE REVIEW

**Comment by amshali** [comment]
why did you close it?

**Comment by seanpcoyle** [comment]
D'oh.  Didn't mean to do that.  Is there a way to re-open it?

**Comment by amshali** [comment]
There should be a re-open button shown for you. I don't have it. I guess because you closed it.

**Comment by seanpcoyle** [comment]
That's what I'm seeing too in the GitHub help docs, but I'm not seeing the button.  The help doc says anyone with commit access should be able to re-open, so I'm not sure why it's not showing up.

**Comment by seanpcoyle** [comment]
Under 'issues', I check the box next to the commit and then click 'reopen', but for some reason, it doesn't re-open the issue.

**Comment by amshali** [comment]
no problem. I will merge it manually.

**Comment by seanpcoyle** [comment]
Alright.  Thanks a bunch.  I'll click a little slower next time around ;).

**Comment by amshali** [comment]
Your code is merged.

**Pull request merged**
