### PR TITLE
Made some changes to the margins. Looks better I think.

### PR DESCRIPTION
**Pull request by amshali**
I propose this changes to margin. I think it looks better.

### CODE REVIEW

**Comment by amshali** [comment]
@jtessler 
@laurenyew 
Have a look.

**Comment by ProCynic** [comment]
You shouldn't change the bootstrap.css directly.  Change the less files and recompile booststrap.

**Comment by ProCynic** [comment]
I think the margin's look fine either way.

**Comment by jtessler** [comment]
Looks good to me!

**Comment by amshali** [comment]
Cannot install jshint. It is kinda inconvenient!  Why would I have to compile it for such a small change?

**Comment by ProCynic** [comment]
because the next time someone changes the less and recompiles your changes
will get wiped.
-Geoffrey Parker

On Thu, May 3, 2012 at 3:25 PM, Amin Shali <
reply@reply.github.com

**Comment by ProCynic** [comment]
do you have npm on you machine?
-Geoffrey Parker

**Comment by amshali** [comment]
My question why would we want to even change the lesses? I see, maybe modularity.... 
I do have npm. It throws an error while installing jshint.

**Comment by ProCynic** [comment]
You change the less because that's really where bootstrap is defined.  You can change one variable in the less files and have stuff change all over bootstrap.css.  The css file is the compiled output, and it will get wiped the next time someone makes bootstrap.  As for npm, I don't know what's wrong with your setup.  Are you using nvm to manage node versions?  If not you should.  Try a fresh install of 6.16; I know jshint installed just fine with 6.15 on my machine a few days ago.

**Comment by amshali** [comment]
the version might be the problem then. I installed ubuntu 11.10 package  and that might be old. Thanks. I'll try...

**Comment by ProCynic** [comment]
ugh, don't use tool versions in repositories, especially for fast changing things like node. Here's how you're supposed to do it:
`cd /usr/local` Or wherever you want to put it
`git clone git://github.com/creationix/nvm.git`
Now you need the packages nvm needs that ubuntu doesn't have by default.  I think it's just:
`sudo apt-get install curl libssl-dev`
but you might also need: `build-essential openssl pkg-config`
Now add this to your `.bashrc` file: `. /usr/local/nvm/nvm.sh` 
Make sure to change that if you put it in a different directory.
Now start up a new shell and say:  `nvm install v0.6.16`
and when that finishes: `nvm alias default 0.6`
At which point you should have the latest version and be able to just `npm install -g less recess jshint uglify-js`

**Comment by amshali** [comment]
Just did! Thanks.

**Comment by ProCynic** [comment]
Looks good.

**Pull request merged**
