### PR TITLE
Fuzzy dates using timeago

### LINKED ISSUE #145: Show fuzzy dates and times
Use this jQuery plugin for showing dates:
http://timeago.yarp.com/

### PR DESCRIPTION
**Pull request by jtessler**
Switched current fuzzy date efforts to use the jQuery plugin, timeago: http://timeago.yarp.com/.

Fixed #145

### CODE REVIEW

**Comment by amshali** [comment]
Can you tell me where is this photoi with id = 2? I wanna replace it with something i have created.

**Comment by jtessler** [comment]
I'm not sure if that was meant for this pull request, but the first few photos are created when the application starts in `apps/utils/Bootstrap.java` (there has to be a cleaner solution, btw...).

**Comment by amshali** [comment]
Yeah, I figured.

**Comment by amshali** [comment]
Comment doesn't work! I think it might be the result of the latest change.

**Comment by amshali** [comment]
I fixed #175.

**Pull request merged**
