### PR TITLE
Set #header and #content width to 980px

### PR DESCRIPTION
**Pull request by astolarz**
Sorry for the long delay.

### CODE REVIEW

**Comment by astolarz** [comment]
Lauren: feel free to change the names to whatever you feel is best.

**Comment by ghost** [comment]
I have a small suggestion. Can you add {position:fixed;} for the orange_bar? When the user scrolls, the top bar will stay in view. It's more like facebook's bar and I think it looks a little smoother. Thanks

**Comment by amshali** [comment]
could you please redo this with the latest repo? Lauren moved main.css and it has changed since your change.

**Comment by astolarz** [comment]
Why is main.css in app/views/stylesheets? Why does app/views/stylesheets exist? That's what public/stylesheets is for. See [here](http://www.playframework.org/documentation/1.1/tags#stylesheet) for examples of proper usage.

**Comment by amshali** [comment]
Hi @laurenyew 
What do you think?

**Comment by laurenyew** [comment]
Hi @amshali and @metrion 
Can you check that you have done git pull upstream master on what you are checking in?
It looks okay, but it doesn't look like this version has my change of the href of stylesheets/main.css to Skins.stylesheet() that is in the current w7cook/master. Just making sure this doesn't have an old version that may mess with everyone's code.

**Comment by amshali** [comment]
@metrion says that main.css must be in public/stylesheets. Can you move it there?

**Comment by amshali** [comment]
@metrion @laurenyew 
guys, pull from upstream master. I fixed it.

**Comment by laurenyew** [comment]
@amshali What happened to my app/views/stylesheets/main.css?

**Comment by astolarz** [comment]
@laurenyew Now I see why you might have thought to put main.css in app/views, since you have it being changed dynamically. I think a better way to go about this would be to pull out the skin code from main.css into a separate stylesheet (perhaps call it skin.css). skin.css would only have dynamic rules, nothing static. This way you could create classes in the views for the customizable parts (for example, create a .custom-font class, so you could change the font for all objects with that class with one rule).

I could explain this a lot better in person if you would like to meet up (I'm in ENS lab now if you can, but otherwise I won't really be available until after 7pm tomorrow).

**Comment by laurenyew** [comment]
@metrion I can't make it today or tomorrow. Do you want to meet up with Geoffrey and me on Thursday at 2pm at the FAC common room (behind the front desk)? We're going to be discussing making the main.css and other htmls more efficient anyways.

**Comment by amshali** [comment]
Can you fix the issues and open the request again? Thanks

**Pull request closed without merging**
