### PR TITLE
Fixed jquery that birthdays broke.  Birthdays needs to be fixed.

### PR DESCRIPTION
**Pull request by ProCynic**
The script in birthdays broke jquery.

### CODE REVIEW

**Comment by amshali** [comment]
It broke what in jQuery? What is wrong with that?

**Comment by ProCynic** [comment]
It undefined $
-Geoffrey Parker

On Tue, May 1, 2012 at 2:13 PM, Amin Shali <
reply@reply.github.com

**Comment by ghost** [comment]
Amin and I talked about it -- I'll be moving the javascript into the rhsNav, and that should fix it up

**Comment by ProCynic** [comment]
As long as `jquery.noConflict()` is not present it doesn't matter where it is.

**Pull request merged**
