### PR TITLE
Thumbnail quality improvements.

### PR DESCRIPTION
**Pull request by jtessler**

### CODE REVIEW

**Comment by ProCynic** [comment]
Do we have height and width attributes on the image tags in the html?  If not they should be added.

**Comment by jtessler** [comment]
I removed them because the thumbnail size remains constant. I figured adding `width="120" height="120"` would be unnecessary because the image is never anything but 120x120. Is there a reason to keep them there?

**Comment by ProCynic** [comment]
it speeds up page load time and prevent's the layout from moving around as
the images get loaded.
-Geoffrey Parker

On Fri, Apr 27, 2012 at 12:29 AM, Joe Tessler <
reply@reply.github.com

**Comment by jtessler** [comment]
Interesting - I didn't know that. I'll add them all back now.

**Comment by amshali** [comment]
let me test this ....

**Comment by amshali** [comment]
You know, we can still make it bigger. Like 150x150. It is okay to increase its size. Page would look better with some appropriately sized photos.

**Pull request merged**
