### PR TITLE
Merge Group Feature

### PR DESCRIPTION
**Pull request by kschloss**
I added basic group functionality. I still have problems getting a User to own more than one Group or getting a User to be a member of more than one Group. I spent a good amount of time trying to figure this out but couldn't so I am in need of some help. There is no way for a User to join or edit groups yet.

### CODE REVIEW

**Comment by amshali** [comment]
There is something wrong with this commit. You are checking in all the files of the project. Please get the latest version of the project by running:
git pull upstream master

**Comment by kschloss** [comment]
I am confused about what I did to update all the files in my commit. I was
able to do git pull upstream master to where it says I am up to date with
w7cook. When I pushed to my fork I still have the old commit plus the new
one from merging. Should I open a new pull request? Or is there more stuff
I need to do to clean up my fork?
On Mar 21, 2012 12:50 AM, "amshali" <
reply@reply.github.com>
wrote:

**Comment by amshali** [comment]
I think we need to sit together and see what is wrong with this. I have no clue.

**Comment by kschloss** [comment]
Well I fixed the repository by deleting my fork and reinserting the changes I had made. I think the problem was that I did "git add ." when I was merging with upstream master the first try. It still doesn't make sense to me because I though "git add ." only staged the changed files. Anyway I will open another Pull Request with my new fork.

**Pull request closed without merging**
