### PR TITLE
Fixed new users posting

### PR DESCRIPTION
**Pull request by ellio**
Posts by new users should now be seen by themselves.

### CODE REVIEW

**Comment by amshali** [comment]
have you tested it?

**Comment by ellio** [comment]
Yes - it works

**Comment by ellio** [comment]
yes - it works.

On Fri, Apr 13, 2012 at 12:55 PM, amshali <
reply@reply.github.com

**Comment by ellio** [comment]
Actually - don't pull.  This breaks the photo tests, let me figure out why.

**Comment by amshali** [comment]
Okay, I'll hold on to it.

**Comment by ellio** [comment]
All has been figured out.  Existing tests pass - going to merge in an hour if nobody has any complaints, or if you want to merge now feel free to.

**Comment by amshali** [comment]
Looks good to me.

**Pull request merged**
