### PR TITLE
Added UI for list of friends. Changed profilePhoto and gravatarPhoto to Photo objects. Added email input for gravatar. Fixed SetProfilePhoto button

### LINKED ISSUE #157: Better UI for list of friends
We need a list of friends with the picture of each friend next to them. Also if we can replace that "remove friend" with a icon that would be great. 
Add in:
Different colors per column.
icon for each friends picture
name
Remove friend
Table format

### LINKED ISSUE #208: Allowing users to choose a gravatar email.
It is good as it is now but that would be better if we allow them to use a gravatar email that they have already setup which is different from the one they use in OpenBook. I would say when they click on Use Gravatar, a popup box shows up and asks for their gravatar email. Then we use that one.

### PR DESCRIPTION
**Pull request by laurenyew**
Fixed #208
Fixed #157
Added to messages #147

### CODE REVIEW

**Comment by amshali** [comment]
Well done. Have you tested it?

**Comment by amshali** [comment]
I am gonna merge this for now.

**Comment by laurenyew** [comment]
I tested the UI for this.

**Comment by amshali** [comment]
The list of friends still need some work.

**Comment by laurenyew** [comment]
What else does it need?

**Pull request merged**
