### PR TITLE
Started converting layout to bootstrap.

### PR DESCRIPTION
**Pull request by ProCynic**
Just changed the layouts.  Everything that worked before still works now.

### CODE REVIEW

**Comment by amshali** [comment]
You know, it looks good, but trying resizing the window. The left and right navbars looks awkward. They shrink too much I think.
In addition, I think there is too much margin for posts and comments. Looking at the page, only the first post occupies a lot of space. Doesn't look that pretty. It's not elegant I think.

**Comment by ProCynic** [comment]
It uses row-fluid, which decides the width of the span proportionally.  It looks fine on a large screen, but if you try to significantly narrow it it gets pretty ugly.  I think I can do something to improve it a bit, but small screens are going to be awkward no matter what.

What do you mean too much margin?  Where?

**Comment by amshali** [comment]
I mean this:
http://i49.tinypic.com/2d0c7ec.jpg

**Comment by ProCynic** [comment]
except for the buttons that's intentional.  But I just cut the margins in
half and that's readable too.
-Geoffrey Parker

On Wed, Apr 25, 2012 at 7:15 PM, Amin Shali <
reply@reply.github.com

**Comment by amshali** [comment]
Don't you think the middle column is too wide? Maybe we can increase the width of left and right ones.

**Comment by amshali** [comment]
Or maybe the header can go all the way but the content of the page has a fixed size (say 970px) and is centered?!

**Comment by amshali** [comment]
Could you please pull? I just merged a pull request.

**Comment by ProCynic** [comment]
looks like the pull request you just merged screwed up bootstrap.
-Geoffrey Parker

On Wed, Apr 25, 2012 at 7:35 PM, Amin Shali <
reply@reply.github.com

**Comment by amshali** [comment]
Are you working on a specific branch that I can pull? I am applying patches and it's not fun!

**Comment by ProCynic** [comment]
ok, merged in latest changes.  Are there any other things that make this unpullable?

**Comment by amshali** [comment]
I am guessing some merge  conflict .

**Comment by ProCynic** [comment]
Anything else?

**Pull request merged**
