### PR TITLE
Site-wide thumbnail system

### PR DESCRIPTION
**Pull request by jtessler**
For every image upload, the system creates three thumbnails, 120 x 120, 50 x 50, and 30 x 30. Every `` block that previously shrank the original image, e.g. post/comment profile photos, now uses a thumbnail. This greatly improves load times and prevents "warping" of small images that broke aspect ratios.

I also included a unit test that verifies the thumbnail functionality.

Note: this feature requires another `play dependencies` call.

### CODE REVIEW

**Comment by amshali** [comment]
sounds cool. Trying to test it now.

**Comment by amshali** [comment]
Try this:
Upload a photo and then try to set it as profile picture:
EDIT: try to set it as profile photo from the "Set profile photo" page. Basically click on "Change picture"

Internal Server Error (500) for request GET /photos/setProfilePhoto?submit=Set
Execution exception (In /app/controllers/Photos.java around line 109)
IllegalArgumentException occured : id to load is required for loading

play.exceptions.JavaExecutionException: id to load is required for loading
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:231)
    at Invocation.HTTP Request(Play!)
Caused by: java.lang.IllegalArgumentException: id to load is required for loading
    at org.hibernate.event.LoadEvent.<init>(LoadEvent.java:89)
    at org.hibernate.event.LoadEvent.<init>(LoadEvent.java:61)
    at org.hibernate.impl.SessionImpl.get(SessionImpl.java:1002)
    at org.hibernate.impl.SessionImpl.get(SessionImpl.java:998)
    at org.hibernate.ejb.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:614)
    at org.hibernate.ejb.AbstractEntityManagerImpl.find(AbstractEntityManagerImpl.java:589)
    at play.db.jpa.JPQL.findById(JPQL.java:36)
    at models.Photo.findById(Photo.java)
    at controllers.Photos.setProfilePhoto(Photos.java:109)
    at play.mvc.ActionInvoker.invokeWithContinuation(ActionInvoker.java:548)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:502)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:478)
    at play.mvc.ActionInvoker.invokeControllerMethod(ActionInvoker.java:473)
    at play.mvc.ActionInvoker.invoke(ActionInvoker.java:161)
    ... 1 more

**Comment by jtessler** [comment]
Error confirmed. However, the same thing happens on the current master branch. I'll open an issue for @laurenyew to look into.

**Comment by amshali** [comment]
oh i see. Didn't notice that.
I am gonna merge this...

**Comment by amshali** [comment]
Well done.

**Pull request merged**
